//! Dispatch — routes a marshalled call to the order-preserving trampoline
//! (architecture-independent).
//!
//! Arguments are split into `ints`/`floats` carrier slices purely as a
//! transport; the trampoline table (`crate::platform::Invoke`, generated by
//! build.rs) restores the callee's DECLARED argument order, so rustc emits
//! ABI-correct register assignment for every platform (Win64 assigns
//! registers by parameter position — regrouping int/float there calls with
//! the wrong registers; see platform/Invoke.rs). This file carries no
//! `#[cfg(target_arch)]` at all.
//!
//! Return values come in two table forms: `_ret_int` (u64 — integer /
//! pointer / void returns) and `_ret_float` (f64 bits — floating returns).
//!
//! Limitations:
//! - The declared-argument count is bounded by the generated table's coverage
//!   (`Invoke::MAX_FFI_ARGS`); exceeding it returns `Err`.

use super::Sig::{AbiSig, AbiSlot, AbiType, RetSlot};
use crate::platform::Invoke;

/// Entry point: classify the marshalled slots (building the declared-order
/// pattern), dispatch through the trampoline, and assemble the RetSlot.
pub fn dispatch(
    sig: &AbiSig,
    fn_ptr: *mut core::ffi::c_void,
    args: &[AbiSlot],
) -> Result<RetSlot, &'static str> {
    debug_assert_eq!(
        args.len(),
        sig.params.len(),
        "dispatch: args.len must match sig.params.len"
    );

    let nargs = sig.params.len();
    if nargs > Invoke::MAX_FFI_ARGS {
        return Err("dispatch: argument count exceeds trampoline table coverage");
    }

    // 1. Split AbiSlots into integer / float carrier slices and record each
    //    argument's class bit (bit i = declared argument i: 0=int, 1=float).
    let mut int_slots: Vec<u64> = Vec::with_capacity(nargs);
    let mut float_slots: Vec<f64> = Vec::with_capacity(nargs);
    let mut classes: u32 = 0;
    for (i, (param, slot)) in sig.params.iter().zip(args.iter()).enumerate() {
        match (param, *slot) {
            (AbiType::Int { .. }, AbiSlot::Int(v)) => int_slots.push(v),
            (AbiType::Int { .. }, AbiSlot::Ptr(p)) => int_slots.push(p as u64),
            (AbiType::Ptr, AbiSlot::Ptr(p)) => int_slots.push(p as u64),
            (AbiType::Ptr, AbiSlot::Int(v)) => int_slots.push(v),
            (AbiType::Float32 | AbiType::Float64, AbiSlot::Float(f)) => {
                classes |= 1 << i;
                float_slots.push(f);
            }
            _ => return Err("dispatch: AbiSlot kind does not match AbiType"),
        }
    }

    // 2. Pattern = sentinel bit | declared-order classes. The generated table
    //    enumerates every mixed pattern up to 8 declared args and only the
    //    all-integer shape beyond that (wide signatures are pointer/length
    //    pairs in practice) — reject a mixed shape past 8 loudly instead of
    //    letting the generated match fall into its unreachable arm.
    if nargs > crate::platform::Invoke::MAX_FFI_FULL_ENUM_ARGS && classes != 0 {
        return Err("dispatch: mixed int/float signature beyond 8 arguments exceeds trampoline table coverage");
    }
    let pattern = (1u32 << nargs) | classes;
    let ret_is_float = matches!(sig.ret, AbiType::Float32 | AbiType::Float64);

    // SAFETY: `fn_ptr` is a valid function pointer guaranteed by the upper
    //         Marshal/Loader layer; `int_slots`/`float_slots` carry one entry
    //         per argument of the matching class, per the classification above.
    let ret_raw = unsafe {
        if ret_is_float {
            Invoke::ffi_invoke_ret_float(pattern, fn_ptr, &int_slots, &float_slots)
        } else {
            Invoke::ffi_invoke_ret_int(pattern, fn_ptr, &int_slots, &float_slots)
        }
    };

    // 3. Assemble RetSlot according to `sig.ret`.
    Ok(match sig.ret {
        AbiType::Void => RetSlot::Void,
        // The trampoline reads the raw 64-bit xmm0 return. A C `float` result
        // lives in the LOW 32 bits (upper bits undefined), so reinterpret those
        // as f32 before widening; a `double` result uses all 64 bits.
        AbiType::Float32 => RetSlot::Float(f64::from(f32::from_bits(ret_raw as u32))),
        AbiType::Float64 => RetSlot::Float(f64::from_bits(ret_raw)),
        AbiType::Int { .. } | AbiType::Ptr => {
            // Integer / pointer return; the low 64 bits of `ret_raw` are the value.
            RetSlot::Int(ret_raw)
        }
    })
}
