//! Symbols — stdlib C symbol address cache (replaces the deleted `bindings_addr`
//! hardcoded table).
//!
//! stdlib `@extern("C") #{ }#` functions are compiled and linked into the frond
//! binary by build.rs. Resolution order:
//!
//! 1. The symbol registry table generated by build.rs (`frond_extern_registry.rs`
//!    in OUT_DIR). Rust-side references to the table are what keeps every
//!    primitive alive through linker dead-stripping (macOS `-dead_strip`, Linux
//!    `--gc-sections`, MSVC `/OPT:REF`); whole-archive linking alone does not.
//! 2. [`platform::ResolveSelfSymbol`] (dlsym/GetProcAddress self-lookup) as a
//!    fallback for anything not in the table.
//!
//! This module layers a lazy cache on top to avoid re-scanning on every FFI call.

use std::sync::OnceLock;

use parking_lot::Mutex;
use rustc_hash::FxHashMap;

// Allow list covers generated extern statics (non_upper_case_globals) and the
// stub variant (unused items) — inner attributes cannot travel through include!.
#[allow(non_upper_case_globals, non_camel_case_types, dead_code, unused_unsafe)]
mod registry {
    include!(concat!(env!("OUT_DIR"), "/frond_extern_registry.rs"));
}

/// Global symbol address cache: symbol name → address (stored as `usize` since
/// raw pointers are not `Send`/`Sync`).
static CACHE: OnceLock<Mutex<FxHashMap<String, usize>>> = OnceLock::new();

/// Resolve a stdlib C symbol address by name.
///
/// The first lookup scans the linked registry table, then falls back to dlsym
/// self-lookup; the result is cached. Returns `None` when the symbol is not
/// found (not linked, or name mismatch).
pub fn resolve(name: &str) -> Option<*mut core::ffi::c_void> {
    let cache = CACHE.get_or_init(|| Mutex::new(FxHashMap::default()));
    // Check the cache first (within read-lock granularity).
    {
        let map = cache.lock();
        if let Some(&addr) = map.get(name) {
            return Some(addr as *mut core::ffi::c_void);
        }
    }
    // Cache miss: registry table first, dlsym self-lookup second.
    let addr = registry::registry_lookup(name)
        .or_else(|| crate::platform::ResolveSelfSymbol::resolve_self_symbol(name))?;
    let addr_usize = addr as usize;
    cache.lock().insert(name.to_string(), addr_usize);
    Some(addr)
}
