//! Invoke — the generated order-preserving FFI trampoline table.
//!
//! The table (generated by `build.rs` into `OUT_DIR/ffi_invoke_table.rs`)
//! dispatches a dynamic C call through a FULLY TYPED `extern "C" fn(...)`
//! whose parameter list preserves the callee's DECLARED argument order. The
//! previous table keyed on `(int_count, float_count)` and grouped all
//! integers before all floats: SysV/AAPCS allocate integer and floating
//! registers per class independently, so the regrouping happened to match —
//! but Win64 assigns registers by parameter POSITION (RCX/RDX/R8/R9 or
//! XMM0..3 for the Nth argument), so any interleaved (float, int) signature
//! received both values from the wrong registers (verified against an
//! MSVC-compiled callee: `f(double, int64_t)` called as `(u64, f64)`
//! returned 0 instead of 42). Pattern-keyed order preservation is correct on
//! every ABI rustc targets — rustc emits the platform-correct prologue for
//! each concrete signature.
//!
//! Pattern encoding: `pattern = (1 << nargs) | classes` where bit `i` of
//! `classes` is the class of declared argument `i` (0 = integer/pointer,
//! 1 = float). The sentinel bit removes the leading-zero ambiguity between
//! "one integer argument" and "zero arguments".

include!(concat!(env!("OUT_DIR"), "/ffi_invoke_table.rs"));
