//! ResolveSelfSymbol — look up symbol addresses by name within the current
//! process (dlsym self-lookup).
//!
//! stdlib `@extern("C") #{ }#` functions are compiled and linked into the frond
//! binary by build.rs; their symbols live in the process itself. At runtime the
//! system dynamic loader resolves symbol addresses by name, with no need for a
//! compile-time binding table (the `bindings_addr` table has been removed).
//!
//! Platform mechanism:
//! - **Linux/macOS**: obtain the main program handle via `dlopen(NULL)`, then
//!   look up by name with `dlsym`. `extern "C"` global symbols appear in the
//!   dynamic symbol table by default and can be looked up directly.
//! - **Windows**: obtain the main .exe's HMODULE via `GetModuleHandle(NULL)`,
//!   then resolve with `GetProcAddress`. Symbols enter the export table via the
//!   C-side `__declspec(dllexport)` (the `FROND_EXPORT` macro, generated by
//!   build.rs).
//!
//! Returns `None` on failure. The caller (`ffi::Symbols`) is responsible for
//! caching, to avoid hitting the system API on every call.

/// Look up a symbol address by name within the current process.
///
/// `None` indicates the symbol was not found (not exported, not linked, or name
/// mismatch).
pub fn resolve_self_symbol(name: &str) -> Option<*mut core::ffi::c_void> {
    // NULL-terminated C string (required by dlsym/GetProcAddress).
    let mut buf: Vec<u8> = Vec::with_capacity(name.len() + 1);
    buf.extend_from_slice(name.as_bytes());
    buf.push(0);

    #[cfg(unix)]
    {
        // SAFETY: `dlopen(NULL)` opens the main program and is safe; `dlsym` for
        //        symbol lookup does not trigger undefined behavior (the symbol
        //        type is guaranteed correct by the caller).
        unsafe {
            extern "C" {
                fn dlopen(filename: *const core::ffi::c_char, flag: i32) -> *mut core::ffi::c_void;
                fn dlsym(handle: *mut core::ffi::c_void, symbol: *const core::ffi::c_char) -> *mut core::ffi::c_void;
            }
            const RTLD_DEFAULT: *mut core::ffi::c_void = (-2isize) as *mut core::ffi::c_void;
            // RTLD_DEFAULT makes dlsym search every loaded module (equivalent to
            // the handle semantics of dlopen(NULL), but with no need to close).
            // Both macOS and Linux support RTLD_DEFAULT (Linux uses a different
            // value, hence dlopen(NULL)).
            #[cfg(target_os = "macos")]
            let handle: *mut core::ffi::c_void = RTLD_DEFAULT;
            #[cfg(not(target_os = "macos"))]
            let handle: *mut core::ffi::c_void = {
                const RTLD_NOW: i32 = 2;
                dlopen(core::ptr::null(), RTLD_NOW)
            };
            if handle.is_null() {
                return None;
            }
            let addr = dlsym(handle, buf.as_ptr() as *const core::ffi::c_char);
            if addr.is_null() { None } else { Some(addr) }
        }
    }

    #[cfg(windows)]
    {
        // SAFETY: `GetModuleHandle(NULL)` returns the main .exe's HMODULE (it
        //        does not increment the reference count, so no FreeLibrary is
        //        needed); `GetProcAddress` queries the export table and returns
        //        NULL on a miss.
        unsafe {
            extern "system" {
                fn GetModuleHandleW(lpModuleName: *const u16) -> *mut core::ffi::c_void;
                fn GetProcAddress(hModule: *mut core::ffi::c_void, lpProcName: *const u8) -> *mut core::ffi::c_void;
            }
            let handle = GetModuleHandleW(core::ptr::null());
            if handle.is_null() {
                return None;
            }
            let addr = GetProcAddress(handle, buf.as_ptr());
            if addr.is_null() { None } else { Some(addr) }
        }
    }

    #[cfg(not(any(unix, windows)))]
    {
        let _ = buf;
        None
    }
}
