//! FFI bindings module (auto-generated by `build.rs`).
//!
//! `bindings` and `wrapper` are auto-generated by `build.rs` from `builtin/*/Raw.kz`:
//! - `kuzo emit-c` generates `.c` files, compiled by `cc` into the `kuzo_extern` static library.
//! - `kuzo emit-ffi` generates Rust FFI code (`bindings` + `wrapper`), written to `$OUT_DIR/ffi_generated.rs`.
//!
//! If there are no `@extern("C")` `.kz` files under `builtin/`, this module is empty.
//!
//! ## Usage
//!
//! 1. Declare `@extern("C")` functions in `builtin/{io,net,time,cast}/Raw.kz`.
//! 2. Run `cargo build` (first build of the `kuzo` binary).
//! 3. Run `cargo build` again (auto-extract C + generate FFI + compile and link).
//!
//! ## Invocation
//!
//! On the Kuzo side, call directly by function name: `__stdout_write("hello")`.
//! On the Rust side, call the wrapper: `unsafe { kuzo_rs::Ffi::wrapper::__stdout_write("hello") }`.

include!(concat!(env!("OUT_DIR"), "/ffi_generated.rs"));
