#![allow(non_snake_case)]
//! ffi — Foreign Function Interface modules.
//!
//! Aggregates two FFI-related submodules:
//! - [`ExternC`]: `@extern("C")` extractor + Rust FFI wrapper generator. Scans
//!   the parsed AST, extracts extern C declarations, and generates C source
//!   files plus Rust FFI binding code.
//! - [`Ffi`]: Generated FFI bindings (auto-generated by `build.rs` from
//!   `builtin/*/Raw.kz`). Contains `bindings` and `wrapper` submodules
//!   included from `$OUT_DIR/ffi_generated.rs`. Empty when no `@extern("C")`
//!   `.kz` files are present under `builtin/`.

pub mod ExternC;
pub mod Ffi;

/// 属性名常量（单点维护，消除字符串字面量散布）
pub const ATTR_EXTERN: &str = "extern";
pub const ATTR_C_INCLUDE: &str = "c_include";
